<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		//TODO do something before all the action
	}
	
	public function run() {
		$this->setOutput(Wekit::C('site', 'search.isopen'), "isopen");
		$this->setOutput($this->_loadMedzServer()->medz("search"), 'search');
	}
	
	/**
	 * 保存搜索设置
	 *
	 */
	public function doRunAction() {
		$isopen			  = $this->getInput('isopen', 'post');
		$search['s']	  = $this->getInput("s", "post");
		$search['entry']  = $this->getInput("entry", "post");
		$search['domain'] = $this->getInput("domain", "post");
		$this->_loadMedzServer()->medz("search", false, true, $search);
		$config = new PwConfigSet('site');
		$config->set('search.isopen', $isopen);
		$config->flush();
		$this->showMessage('success');
	}
	
	private function _loadMedzServer() {
		return Wekit::load('EXT:search.service.helps.App_Medz_Server');
	}
	
}
